package net;

public class Constants {
	public static final int COMMUNITY_MODE = 0x01;
	public static final int TEAMPLAY_MODE = 0x03;
	public static final int SURVIVAL_MODE = 0x04;
	public static final int DUEL_MODE = 0x05;
	public static final int LUCKY_3_MODE = 0x06;
	public static final int ASSAULT_MODE = 0x07;
	public static final int SOCCER_MODE = 0x08;
	public static final int KING_SLAYER = 0x09;
	public static final int MAGIC_LUCKY_3 = 0x0A;
	public static final int DUNGEON_QUEST_1 = 0x0B;
	public static final int DUNGEON_QUEST_2 = 0x0C;
	public static final int DUNGEON_QUEST_3 = 0x0D;
	public static final int DUNGEON_QUEST_4 = 0x0E;
	public static final int FIGHT_CLUB_MODE = 0x0F;
	public static final int TOURNAMENT_MODE = 0x10;
	public static final int DUNGEON_QUEST_5 = 0x11;
	public static final int FOREST_QUEST_1 = 0x12;
	public static final int FOREST_QUEST_2 = 0x13;
	public static final int FOREST_QUEST_3 = 0x14;
	public static final int FOREST_QUEST_4 = 0x15;
	public static final int FOREST_QUEST_5 = 0x16;
	public static final int FLAME_QUEST_1 = 0x17;
	public static final int FLAME_QUEST_2 = 0x18;
	public static final int FLAME_QUEST_3 = 0x19;
	public static final int FLAME_QUEST_4 = 0x1A;
	public static final int FLAME_QUEST_5 = 0x1B;
	public static final int DODGE_MODE = 0x1C;
	public static final int MOLE_MODE = 0x1D;
	public static final int RACING_MODE = 0x1E;
	public static final int SYMBOL_MODE = 0x1F;
	public static final int K_SURVIVAL_MODE = 0x20;
	public static final int BB_SURVIVAL = 0x21;
	public static final int BM_AUTO = 0x22;
	public static final int BM_DEATH_MATCH = 0x23;
	public static final int CRYSTAL_MODE = 0x28;
	public static final int HOKEY_MODE = 0x29;
	public static final int MISSION_TRAINING = 0x2E;
	public static final int MISSION_MODE = 0x2F;
	public static final int INFINITY_SURVIVAL = 0x30;
	public static final int INFINITY_SYMBOL = 0x31;
	public static final int INFINITY_KING = 0x32;
	public static final int HERO_MODE = 0x33;
}
